import re
import timeit

from Puzzles.Tapa.TapaGame import TapaGame
from Utils.Grid import Grid


class TapaBenchmark:
    def __init__(self):
        self.grids6x6_normal = [
            [[False, False, False, False, False, False], [False, [7], False, False, [6], False], [False, False, [1, 2], [1, 1], False, False], [False, False, [1, 2], [1, 1], False, False], [False, [1, 4], False, False, [5], False],
             [False, False, False, False, False, False]],
            [[False, False, False, False, False, False], [False, [1, 3], [1, 2], False, [1, 5], False], [False, False, False, False, [2, 3], False], [False, [2, 3], False, False, False, False], [False, [7], False, [6], [1, 5], False],
             [False, False, False, False, False, False]],
            [[False, False, False, False, False, False], [[2, 2], [7], False, False, [3, 3], [2, 2]], [False, False, False, False, False, False], [[1, 3], False, False, False, False, [1, 2]], [False, [1, 4], False, False, [6], False],
             [False, False, False, False, False, False]],
            [[False, False, [1, 2], False, [5], False], [False, [1, 4], False, False, False, False], [False, False, False, False, False, False], [False, False, False, False, False, False], [False, False, False, False, [2, 4], False],
             [False, [5], False, [1, 3], False, False]],
            [[False, [5], False, False, [4], False], [False, False, False, False, False, False], [[3], False, False, False, False, [4]], [[1, 2], False, False, False, False, [4]], [False, False, False, False, False, False], [False, [5], False, False, [1, 3], False]],
            [[False, False, False, False, False, False], [False, [2, 3], False, False, [6], False], [False, [7], False, False, [1, 4], False], [False, False, False, False, False, False], [False, False, False, False, False, False],
             [False, False, [1, 2], [1, 2], False, False]],
        ]

        self.grids6x6_hard = [
            [[False, False, False, False, False, False], [False, [7], False, [1, 4], [1, 4], False], [False, [3, 3], False, False, False, False], [False, False, False, False, [2, 4], False], [False, [1, 2, 2], [6], False, [7], False],
             [False, False, False, False, False, False]],
            [[False, [4], False, False, [5], False], [False, False, False, False, False, False], [[1, 2], False, False, False, False, [1, 2]], [False, [1, 2], False, False, [2, 3], False], [False, False, False, False, False, False],
             [False, False, False, False, False, False]],
            [[False, False, False, [1, 2], [4], False], [[4], False, False, False, False, False], [[1, 2], False, False, False, False, False], [False, False, False, False, False, [3]], [False, False, False, False, False, [4]], [False, [4], [1, 2], False, False, False]],
            [[False, [5], False, False, [1, 3], False], [False, False, False, False, False, False], [False, [6], False, False, [7], False], [False, False, False, False, False, False], [[3], False, False, False, False, [4]], [False, False, False, False, False, False]],
        ]

        self.grids10x10_normal = [
            [[False, False, False, False, False, False, False, False, False, False], [False, False, [3, 3], [2, 3], False, False, [2, 4], [2, 3], False, False], [False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [6], False, False, [4], False, False, False], [[3], False, [1, 3], False, False, False, False, [1, 4], False, [4]], [[1, 2], False, [1, 1, 2], False, False, False, False, [1, 3], False, [4]],
             [False, False, False, [1, 4], False, False, [6], False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, False, [3, 3], [2, 3], False, False, [2, 4], [2, 4], False, False],
             [False, False, False, False, False, False, False, False, False, False]],
            [[False, [5], False, [4], False, False, [5], False, [2, 2], False], [False, False, False, False, False, False, False, False, False, False], [False, False, False, False, [1, 4], [1, 3], False, False, False, False],
             [False, False, [1, 2], False, False, False, False, [5], False, False], [[5], False, False, [5], False, False, [1, 2], False, False, [4]], [False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False], [False, [2, 3], False, False, False, False, False, False, [2, 4], False], [False, False, [1, 1, 2], False, False, False, False, [1, 1, 3], False, False],
             [False, False, False, [1, 2], False, False, [1, 3], False, False, False]],
            [[[3], False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, [3, 3], False, False, False], [False, False, [1, 1, 3], False, False, False, False, False, [1, 1, 3], False],
             [[3], False, False, False, [7], False, False, [2, 3], False, False], [False, False, False, False, False, [1, 1, 2], False, False, False, [4]], [[1, 3], False, False, False, [1, 4], False, False, False, False, False],
             [False, False, [6], False, False, [6], False, False, False, [5]], [False, [1, 3], False, False, False, False, False, [6], False, False], [False, False, False, [3, 3], False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [1, 1]]],
            [[[1, 1], False, False, False, False, False, False, False, False, [1, 1]], [False, False, False, False, False, False, False, [3, 3], False, False], [False, [7], False, False, False, [1, 1, 2], False, False, False, False],
             [False, False, False, [6], False, False, [3], False, False, False], [False, False, [1, 4], False, False, False, False, False, False, False], [False, False, False, False, False, False, False, [1, 2], False, False],
             [False, False, False, [2, 3], False, False, [2, 3], False, False, False], [False, False, False, False, [1, 4], False, False, False, [7], False], [False, False, [2, 3], False, False, False, False, False, False, False],
             [[1, 1], False, False, False, False, False, False, False, False, [1, 1]]],
            [[False, False, False, False, [3], False, False, False, False, False], [False, [7], False, False, False, False, False, False, False, False], [[1, 1, 1], False, False, False, [6], False, False, False, [3], False],
             [False, [2, 3], False, False, False, False, False, False, [3], False], [False, [1, 1, 3], False, False, False, [7], False, False, False, False], [False, False, False, False, [2, 3], False, False, False, [2, 3], False],
             [False, [3, 3], False, False, False, False, False, False, [2, 4], False], [False, [2, 3], False, False, False, [1, 1, 3], False, False, False, [1, 1, 1]], [False, False, False, False, False, False, False, False, [2, 4], False],
             [False, False, False, False, False, [1, 3], False, False, False, False]],
        ]

        self.grids10x10_hard = [
            [[[2], False, False, False, False, False, [5], False, False, [2]], [False, False, False, False, [7], False, False, False, False, False], [False, False, [2, 4], False, False, False, False, [2, 3], False, False],
             [[1, 3], False, False, [3, 3], False, False, [3], False, False, False], [False, False, False, False, False, False, False, False, [7], False], [False, [7], False, False, False, False, False, False, False, False],
             [False, False, False, [2, 2], False, False, [2, 2], False, False, [1, 3]], [False, False, [6], False, False, False, False, [1, 5], False, False], [False, False, False, False, False, [7], False, False, False, False],
             [[1], False, False, [5], False, False, False, False, False, [2]]],
            [[False, False, False, False, False, False, False, False, False, False], [False, False, [1, 4], [1, 1, 2], False, False, [2, 4], [2, 3], False, False], [False, [7], False, False, False, False, False, False, [1, 3], False],
             [False, False, False, False, False, False, False, False, False, False], [False, False, [5], [1, 3], False, False, [2], [2], False, False], [False, False, [5], [4], False, False, [1, 2], [5], False, False],
             [False, False, False, False, False, False, False, False, False, False], [False, [7], False, False, False, False, False, False, [6], False], [False, False, [1, 4], [1, 2, 2], False, False, [2, 2], [1, 4], False, False],
             [False, False, False, False, False, False, False, False, False, False]],
            [[False, False, False, [3], False, False, [2, 2], False, False, False], [[1, 2], [1, 4], False, False, False, False, False, False, [6], [1, 2]], [False, False, False, False, False, False, False, False, False, False],
             [False, False, [3, 3], False, False, False, False, [2, 4], False, False], [[4], False, False, False, [1, 3], [4], False, False, False, [4]], [[3], False, False, False, [5], [2, 2], False, False, False, [4]],
             [False, False, [7], False, False, False, False, [1, 5], False, False], [False, False, False, False, False, False, False, False, False, False], [[2, 2], [2, 4], False, False, False, False, False, False, [1, 4], [1, 2]],
             [False, False, False, [5], False, False, [1, 3], False, False, False]],
            [[False, False, False, False, False, False, False, [1, 3], False, False], [[2, 2], False, False, False, False, False, [1, 4], False, False, [4]], [False, False, False, [1, 4], False, False, False, False, False, False],
             [[2, 2], False, False, False, False, False, False, False, False, False], [False, False, False, [1, 3], [1, 3], False, False, False, False, [5]], [[2, 2], False, False, False, False, [1, 2], [1, 1], False, False, False],
             [False, False, False, False, False, False, False, False, False, [5]], [False, False, False, False, False, False, [6], False, False, False], [[4], False, False, [2, 3], False, False, False, False, False, [2, 2]],
             [False, False, [1, 2], False, False, False, False, False, False, False]],
            [[[1, 1], False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False], [False, [6], False, False, [1, 5], False, False, [1, 1, 1], False, False],
             [False, False, False, False, False, False, False, False, [6], False], [[5], False, [7], False, False, [1, 3], False, False, False, False], [False, False, False, False, [1, 3], False, False, [2, 2], False, [1, 2]],
             [False, [7], False, False, False, False, False, False, False, False], [False, False, [1, 1, 1], False, False, [2, 4], False, False, [6], False], [False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [2]]],
        ]

        self.grids15x15 = [
            [[False, False, False, False, False, [5], False, False, False, False, False, False, False, [1, 1], False], [[4], False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, [3]],
             [False, False, False, [1, 4], False, False, False, False, [1, 2, 2], [2, 4], False, [1, 2], False, False, False], [False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, [6], False, False],
             [False, [6], False, False, False, False, [1, 2], False, False, [5], [1, 1, 2], False, False, False, False], [[1, 2], False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [6], False, False, False, False, [2, 4], False, [3, 3], False, [4], [1, 3], False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [1, 1, 1, 1], [5], False, [7], False, [3, 3], False, False, False, False, [1, 2, 2], False, False, False], [False, False, False, False, False, False, False, False, False, False, [1, 2, 2], False, False, False, [1, 3]],
             [False, False, False, False, [1, 1, 2], [1, 4], False, False, [1, 2], False, False, False, False, [2, 4], False], [False, False, [1, 2], False, False, False, False, False, [1, 1, 3], False, False, False, False, False, False],
             [False, False, False, [2, 3], False, [5], [2, 2], False, False, False, False, [7], False, False, False], [[1, 1], False, False, False, False, False, False, False, False, False, False, False, [1, 5], False, [5]],
             [False, [3], False, False, False, False, False, False, False, [1, 2], False, False, False, False, False]],
            [[[2], False, [1, 2], False, False, [2], False, False, False, [2, 2], False, False, [1, 2], False, [2]], [False, False, [1, 5], False, False, False, False, [1, 4], False, False, False, False, [1, 1, 3], False, False],
             [[1, 2], False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, [4]], [False, False, False, [1, 5], False, [7], False, False, False, [6], False, [1, 5], False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, [3, 3], False, False, [1, 4], False, False, [1, 1, 2], False, False, [7], False, False, [6], False],
             [False, False, False, False, False, False, [7], False, [2, 3], False, False, False, False, False, False], [False, [2, 3], False, False, False, False, False, False, False, False, False, False, False, [6], False],
             [False, False, [1, 1, 2], False, False, False, [6], False, [2, 2], False, False, False, [3], False, False], [False, False, [1, 3], False, [6], False, False, [1, 1, 1], False, False, [1, 4], False, [1, 3], False, False],
             [False, False, False, False, False, [1, 4], False, False, False, [1, 4], False, False, False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [3], False, False, [6], False, False, False, [7], False, False, [1, 1, 1], False, False], [False, False, [2], False, False, False, [3], False, [1, 3], False, False, False, [1, 3], False, False],
             [False, False, False, False, [3], False, False, False, False, False, [4], False, False, False, False]],
            [[[3], False, False, [1, 1, 1], False, False, False, False, False, False, False, [1, 3], False, False, [2]], [False, False, False, False, [3, 3], False, False, False, False, False, [1, 1, 2], False, False, False, False],
             [[5], False, False, False, False, [7], False, [7], False, [2, 3], False, False, False, False, [2, 2]], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [6], False, False, False, False, False, False, False, False, False, [7], False, False], [[1, 2], False, False, False, False, False, [1, 1, 2], False, [1, 4], False, False, False, False, False, [1, 1]],
             [False, [7], False, [7], False, False, [1, 1, 2], False, [1, 1, 1], False, False, [7], False, [2, 3], False], [False, False, False, False, False, False, [6], False, [1, 4], False, False, False, False, False, False],
             [False, False, False, [3, 3], False, False, False, False, False, False, False, [3, 3], False, False, False], [False, False, False, False, False, [7], False, False, False, [1, 5], False, False, False, False, False],
             [False, [7], False, [1, 2, 2], False, False, False, False, False, False, False, [1, 2, 2], False, [6], False], [False, False, False, [2, 3], False, False, False, False, False, False, False, [2, 3], False, False, False],
             [False, False, [1, 1, 2], False, False, [2, 4], False, False, False, [6], False, False, [1, 1, 2], False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [2, 2], False, False, False, [2, 2], False, False, False, [1, 3], False, False, False, [2, 2], False]],
            [[[1, 1], False, False, False, False, False, False, [1, 1], False, False, False, False, [1, 3], False, [3]], [False, [2, 2], False, [5], False, False, False, False, [4], False, False, [1, 2, 2], False, False, False],
             [False, False, False, False, False, [1, 5], False, [1, 3], False, False, False, False, False, False, False], [False, [6], False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 1]],
             [False, False, False, False, False, False, [4], False, False, [2, 3], False, [2, 4], False, [2, 4], False], [False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False],
             [[1, 2], False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, False], [False, [7], False, False, False, [2, 3], False, False, False, [1, 3], False, False, False, [2, 4], False],
             [False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, [1, 2]], [False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, False, False],
             [False, [1, 2, 2], False, [1, 2, 2], False, [1, 1, 2], False, False, [5], False, False, False, False, False, False], [[1, 2], False, False, False, False, False, False, False, False, False, False, False, False, [7], False],
             [False, False, False, False, False, False, False, [1, 4], False, [2, 3], False, False, False, False, False], [False, False, False, [2, 3], False, False, [5], False, False, False, False, [7], False, [2, 4], False],
             [[3], False, [1, 2], False, False, False, False, [1, 2], False, False, False, False, False, False, [1, 1]]],
            [[False, False, False, False, [1, 3], False, False, False, [1, 2], False, False, [5], False, False, False], [False, False, [2, 4], False, False, [1, 4], False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, [1, 1, 2], False, False, False, [7], False, False, False, [1, 4], False], [[5], False, False, False, [4], False, [7], False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [1, 3], False, [1, 1, 2], False, False, [1, 3]], [False, False, [5], False, [1, 3], False, False, False, [1, 2], False, False, False, [1, 2, 2], [2, 4], False],
             [[1, 2], False, False, False, False, [6], False, False, False, False, False, [7], False, False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [7], False, False, False, False, False, [1, 1, 1], False, False, False, False, [1, 2]], [False, [2, 4], [1, 2, 2], False, False, False, [3], False, False, False, [1, 4], False, [1, 5], False, False],
             [[1, 1, 1], False, False, [2, 4], False, [4], False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, False, [7], False, [2, 4], False, False, False, [5]],
             [False, [3, 3], False, False, False, [6], False, False, False, [1, 2, 2], False, False, False, False, False], [False, False, False, False, False, False, False, False, False, [2, 4], False, False, [3, 3], False, False],
             [False, False, False, [5], False, False, [1, 2], False, False, False, [1, 1, 1], False, False, False, False]],
        ]

        self.grids15x15_hard = [
            [[False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, [3]], [[4], False, False, [2, 4], False, [2, 3], False, False, [2, 3], False, [2, 4], False, False, False, False],
             [False, False, False, False, [1, 1, 2], False, False, False, False, False, False, [1, 4], False, False, False], [False, [2, 2], [5], False, False, False, False, [1, 4], False, False, False, False, False, False, [3]],
             [False, False, False, False, False, False, False, False, False, False, [3, 3], False, False, False, False], [False, False, False, False, False, False, False, False, [1, 1, 2], False, False, [1, 1, 2], False, False, False],
             [False, False, [2, 3], [3, 3], False, False, False, [6], False, False, False, False, [2, 2], False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [2, 3], False, False, False, False, [1, 4], False, False, False, [6], [1, 1, 2], False, False], [False, False, False, [1, 1, 2], False, False, [1, 1, 2], False, False, False, False, False, False, False, False],
             [False, False, False, False, [3, 3], False, False, False, False, False, False, False, False, False, False], [[4], False, False, False, False, False, False, [1, 4], False, False, False, False, [1, 5], [6], False],
             [False, False, False, [1, 4], False, False, False, False, False, False, [1, 1, 2], False, False, False, False], [False, False, False, False, [2, 3], False, [2, 3], False, False, [3, 3], False, [1, 4], False, False, [5]],
             [[2], False, False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False]],
            [[False, False, [4], False, False, False, False, [1, 1, 1], False, False, False, False, [5], False, False], [[3], False, False, False, False, False, False, False, False, False, False, False, False, False, [3]],
             [False, False, False, False, False, False, [5], False, [1, 5], False, False, False, False, False, False], [False, [2, 3], False, False, False, False, False, False, False, False, False, False, False, [2, 2], False],
             [False, False, [1, 1, 3], False, False, False, False, False, False, False, False, False, [1, 4], False, False], [False, False, False, False, [1, 1, 2], False, False, [2, 3], False, False, [1, 1, 3], False, False, False, False],
             [False, False, False, False, False, [6], False, [1, 1, 3], False, [2, 4], False, False, False, False, False], [[1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2]],
             [False, False, False, False, [6], False, False, False, False, False, [6], False, False, False, False], [False, [1, 4], False, False, False, False, False, [2, 4], False, False, False, False, False, [1, 3], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, [1, 4], False, False, [1, 1, 3], False, [1, 2, 2], False, [6], False, False, [2, 3], False, False],
             [[2], False, False, False, False, False, False, False, False, False, False, False, False, False, [3]], [[1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2]],
             [False, False, False, False, False, [4], False, [2, 2], False, [4], False, False, False, False, False]],
            [[False, False, False, False, False, False, [4], False, False, False, False, False, False, False, [2]], [False, False, False, [1, 4], False, False, False, False, False, False, False, [1, 4], False, False, False],
             [[5], False, False, False, False, [2, 3], [1, 3], [2, 2], False, False, False, False, False, False, False], [False, False, [1, 5], False, False, False, False, False, False, False, [2, 3], False, [1, 3], [6], False],
             [[1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, [2, 3], False, [2, 3], False, False, False, False, [1, 3], False, False, False, False],
             [False, False, [1, 1, 1], False, False, False, False, False, False, False, False, [2, 2], False, [2, 3], False], [False, False, False, False, False, False, [1, 4], False, [1, 4], False, False, False, False, False, False],
             [False, [2, 3], False, [1, 2], False, False, False, False, False, False, False, False, [1, 1, 1], False, False], [False, False, False, False, [1, 3], False, False, False, False, [6], False, [2, 3], False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 3]], [False, [6], [1, 5], False, [1, 5], False, False, False, False, False, False, False, [7], False, False],
             [False, False, False, False, False, False, False, [1, 1, 1], [1, 2], [1, 3], False, False, False, False, [5]], [False, False, False, [1, 5], False, False, False, False, False, False, False, [2, 4], False, False, False],
             [[1], False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False]],
            [[False, False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False], [False, [7], False, False, False, False, False, False, False, False, False, False, False, [7], False],
             [False, False, False, [1, 1], False, False, False, False, False, False, False, [1, 4], False, False, False], [False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, [1, 4], False],
             [[1, 3], False, [1, 2], False, False, [7], False, False, False, [1, 3], False, False, [1, 3], False, [1, 3]], [False, False, False, [2, 2], False, False, False, False, False, False, False, [1, 2], False, False, False],
             [[5], False, False, False, [2, 3], False, False, False, False, False, [1, 1, 2], False, False, False, [4]], [False, False, False, False, False, False, [2, 4], False, [2, 4], False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, [1, 1, 2], [2, 2], False, False, False, False, False, False, False, False, False, [2, 3], [1, 4], False],
             [False, False, False, False, False, False, [1, 1, 2], False, [1, 2], False, False, False, False, False, False], [False, [1, 1, 2], False, False, [6], False, [1, 3], False, [1, 5], False, [1, 5], False, False, [1, 2], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, False, False, False, False, False, False, [6], False, False, False, False, False, False, False],
             [[3], False, [1, 3], False, False, False, False, False, False, False, False, False, [4], False, [3]]],
            [[False, False, False, False, False, False, False, [4], False, False, False, False, False, False, False], [False, False, False, False, [1, 5], False, False, False, False, False, [7], False, False, False, False],
             [False, [1, 3], False, False, False, [2, 4], False, False, False, [3, 3], False, False, False, [3, 3], False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [[2], False, False, False, False, False, [1, 4], False, [1, 3], False, False, False, False, False, [1]], [False, False, False, False, [6], False, False, False, False, False, [1, 3], False, False, False, False],
             [False, False, [1, 5], False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False], [False, [2, 4], False, [2, 4], False, False, False, False, False, False, False, [2, 2], False, [7], False],
             [False, False, False, False, False, [3, 3], False, False, False, [7], False, False, False, False, False], [False, [7], False, False, False, [2, 4], False, False, False, [2, 4], False, False, False, [7], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], [False, [1, 4], [1, 4], False, False, False, [1, 1, 2], False, [1, 5], False, False, False, [1, 3], [5], False],
             [False, False, [1, 4], False, False, [3], False, False, False, [2, 4], False, False, [4], False, False], [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [1, 2], False, False, [2, 2], False, [5], False, [5], False, [5], False, False, [4], False]],
        ]

        self.grids20x20 = [
            [[False, False, False, False, [2, 2], False, False, [3], False, False, False, False, [4], False, False, [2, 2], False, False, False, False],
             [False, [4], False, False, False, False, False, False, False, [1, 2, 2], [2, 4], False, False, False, False, False, False, False, [1, 3], False],
             [False, [3], False, False, False, False, [7], False, [7], False, False, [1, 5], False, [6], False, False, False, False, [1, 3], False],
             [False, [3], [2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1], [3], False],
             [False, False, False, [2, 2], False, False, False, [1, 3], False, False, False, False, [1, 4], False, False, False, [2, 2], False, False, False],
             [False, False, False, False, [1, 3], False, [6], False, False, False, False, False, False, [6], False, [2, 4], False, False, False, False],
             [[4], False, False, False, False, False, False, False, [6], False, False, [5], False, False, False, False, False, False, False, [3]],
             [False, False, False, False, [2, 3], False, [6], False, False, False, False, False, False, [7], False, [2, 3], False, False, False, False],
             [False, [2, 2], False, False, False, False, False, False, [1, 3], False, False, [6], False, False, False, False, False, False, [1, 4], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [2, 4], [1, 2, 2], False, False, False, False, False, False, False, False, False],
             [[2, 2], [3, 3], [3, 3], False, [1, 1, 1], [4], False, False, False, False, False, False, False, False, [5], [3], False, [1, 1, 1], [1, 1], [1]],
             [False, False, False, False, False, False, False, False, False, [3, 3], [2, 3], False, False, False, False, False, False, False, False, False],
             [False, False, False, False, [1, 4], False, [6], False, False, False, False, False, False, [1, 4], False, [7], False, False, False, False],
             [False, [1, 4], [1, 1, 1], False, False, False, False, [1, 4], False, False, False, False, [2, 3], False, False, False, False, [4], [5], False],
             [False, False, False, False, False, [4], False, False, False, False, False, False, False, False, [2, 4], False, False, False, False, False],
             [False, False, False, False, False, [1, 1], False, False, [6], False, False, [1, 4], False, False, [3, 3], False, False, False, False, False],
             [False, False, [2, 4], [2, 3], False, False, False, False, False, False, False, False, False, False, False, False, [1, 5], [2, 2], False, False],
             [[5], False, False, False, False, False, False, False, [2, 2], False, False, [1, 3], False, False, False, False, False, False, False, [1, 2]],
             [False, False, False, False, [3], False, False, [2], False, False, False, False, [2], False, False, [4], False, False, False, False]],
            [[[3], False, [2], [1], False, False, [5], False, [2, 2], False, False, [2], False, False, False, False, False, False, False, [3]],
             [False, False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, [1, 1, 2], [1, 4], False, False, False, False],
             [False, False, False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, False, [2, 2], False, False, [4]],
             [False, False, [1, 4], False, False, [2, 4], False, False, False, [6], False, False, False, [1, 4], False, False, False, False, False, [3]],
             [False, [2, 4], False, False, False, False, False, False, [1, 3], False, False, [3, 3], False, False, False, False, False, False, False, False],
             [False, [2, 3], False, False, False, False, [2, 3], False, False, False, False, False, False, [4], False, False, [2, 3], False, False, False],
             [False, False, False, [7], False, [2, 3], False, False, False, [3, 3], [2, 2], False, False, False, [1, 2], False, False, False, False, [5]],
             [False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, False, False, [7], False, False],
             [[1, 2], [6], False, False, [6], False, False, [1, 4], False, False, False, False, False, False, False, [2, 3], False, False, False, [2]],
             [False, False, False, False, False, False, [2, 2], False, False, False, False, False, False, [1, 3], False, False, [7], False, False, False],
             [False, False, False, [1, 2, 2], False, False, [1, 3], False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False],
             [[2, 2], False, False, False, [1, 4], False, False, False, False, False, False, False, [1, 4], False, False, [2, 3], False, False, [7], [2, 2]],
             [False, False, [7], False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, False, False, False, False, False],
             [[1, 3], False, False, False, False, [1, 3], False, False, False, [2, 4], [7], False, False, False, [1, 3], False, [7], False, False, False],
             [False, False, False, [5], False, False, [2, 2], False, False, False, False, False, False, [1], False, False, False, False, [2, 3], False],
             [False, False, False, False, False, False, False, False, [6], False, False, [2, 2], False, False, False, False, False, False, [2, 3], False],
             [[2], False, False, False, False, False, [1, 5], False, False, False, [6], False, False, False, [2, 4], False, False, [1, 3], False, False],
             [[2], False, False, [1, 4], False, False, False, False, False, False, False, False, [7], False, False, False, False, False, False, False],
             [False, False, False, False, [2, 4], [2, 3], False, False, [7], False, False, False, False, False, False, False, False, False, False, False],
             [[3], False, False, False, False, False, False, False, [2, 2], False, False, [1, 2], False, [5], False, False, [1, 1], [1, 2], False, [2]]],
            [[False, False, False, False, False, False, False, False, [1, 2], False, False, [1, 3], False, False, False, False, False, False, False, False],
             [False, [7], False, False, False, False, False, [1, 2, 2], False, False, False, False, [1, 2, 2], False, False, False, False, False, [6], False],
             [False, False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, False, [7], False, False, False, False],
             [[1, 2], [1, 1, 2], False, False, False, [2], [4], False, False, False, False, False, False, [1, 4], [1, 1, 2], False, False, False, [2, 2], [2]],
             [[3], False, False, False, False, False, False, [1, 4], False, [6], [1, 2, 2], False, [3, 3], False, False, False, False, False, False, [2]],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [1, 3], [1, 5], False, False, [2, 3], False, [1, 2, 2], False, False, [1, 1, 3], False, [2, 3], False, False, [7], [2, 3], False, False],
             [[1, 2], False, False, False, False, [6], False, False, [2, 2], False, False, [1, 2], False, False, [2, 3], False, False, False, False, [1, 2]],
             [False, False, False, False, False, False, False, [1, 3], [1, 1, 3], False, False, [1, 1], [4], False, False, False, False, False, False, False],
             [False, False, [3], [3], False, False, False, False, False, False, False, False, False, False, False, False, [1, 3], [2], False, False],
             [False, False, [2], [3], False, False, False, False, False, False, False, False, False, False, False, False, [1, 2], [2], False, False],
             [False, False, False, False, False, False, False, [2, 2], [1, 1, 1, 1], False, False, [1, 1, 3], [1, 2], False, False, False, False, False, False, False],
             [[1, 1, 1], False, False, False, False, [1, 5], False, False, [1, 2], False, False, [2, 3], False, False, [1, 2], False, False, False, False, [1, 2]],
             [False, False, [1, 1, 2], [1, 4], False, False, [1, 5], False, [1, 5], False, False, [7], False, [5], False, False, [7], [2, 3], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [[3], False, False, False, False, False, False, [6], False, [1, 5], [2, 3], False, [2, 4], False, False, False, False, False, False, [3]],
             [[1, 2], [2, 3], False, False, False, [2, 4], [2, 3], False, False, False, False, False, False, [1, 1, 2], [1, 2, 2], False, False, False, [1, 1, 2], [1, 2]],
             [False, False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, False],
             [False, [7], False, False, False, False, False, [2, 4], False, False, False, False, [1, 4], False, False, False, False, False, [6], False],
             [False, False, False, False, False, False, False, False, [1, 1, 1], False, False, [1, 3], False, False, False, False, False, False, False, False]],
            [[False, False, False, False, False, False, [1, 2], False, False, [1, 2], False, [5], False, False, False, False, False, False, False, False],
             [False, False, [6], False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, [1, 1, 3], [2, 3], False, False],
             [False, [1, 4], False, False, False, False, False, False, False, [3], False, False, [1, 2], False, False, False, [1, 2], False, False, False],
             [False, False, False, False, False, False, False, False, [1, 2], False, False, [5], [1, 2], False, False, False, False, False, False, False],
             [False, [1, 1, 2], False, False, False, False, [2, 3], False, False, False, False, False, False, [2, 4], False, False, False, [1, 4], [1, 2, 2], False],
             [False, False, [3], False, False, False, False, False, [1, 4], False, False, False, False, False, False, [1, 2, 2], False, False, False, False],
             [[4], False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [5], [1, 1, 3], False, [2, 3], False, [1, 1, 2], False, False, [3, 3], False, False, [2, 3], False, False, False, False, [2, 3], False],
             [False, False, False, False, False, [1, 1, 3], False, False, False, [1, 2, 2], False, False, False, False, False, False, [3, 3], [2, 3], False, False],
             [[1, 2], False, False, False, False, False, False, False, False, False, False, False, [6], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, [4]],
             [False, False, [1, 4], [2, 3], False, False, False, False, False, False, [5], False, False, False, [1, 1, 1, 1], False, False, False, False, False],
             [False, [1, 4], False, False, False, False, [3, 3], False, False, [1], False, False, [6], False, [2, 2], False, [1, 2], [4], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, [5]],
             [False, False, False, False, [6], False, False, False, False, False, False, [6], False, False, False, False, False, [2, 3], False, False],
             [False, [2, 4], [7], False, False, False, [1, 4], False, False, False, False, False, False, [4], False, False, False, False, [2, 3], False],
             [False, False, False, False, False, False, False, [1, 1], [1, 2], False, False, [1, 3], False, False, False, False, False, False, False, False],
             [False, False, False, [1, 2], False, False, False, [1, 1], False, False, [4], False, False, False, False, False, False, False, [3, 3], False],
             [False, False, [2], [1, 1, 1], False, False, False, False, False, False, False, False, False, False, [6], False, False, [2, 4], False, False],
             [False, False, False, False, False, False, False, False, [1, 3], False, [1, 2], False, False, [1, 2], False, False, False, False, False, False]],
            [[False, False, False, False, False, [4], False, False, [1, 3], False, [4], False, False, False, [1, 1, 1], False, False, False, [1, 3], False],
             [[1, 2], False, False, False, False, False, False, False, False, False, False, False, False, [2, 4], False, [2, 4], False, [7], False, False],
             [False, [6], False, False, [1, 5], False, [1, 5], False, False, [7], False, [5], False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, [1, 1, 1, 1], False, False, False, False, False, False, False, False],
             [False, [2, 4], False, False, False, [1, 4], False, False, False, [7], False, False, False, False, False, False, False, [1, 1, 3], False, False],
             [[1, 1, 1], False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, [1, 1, 2], False, False, False, [1, 3]],
             [False, [2, 2], False, False, False, [2, 3], False, [1, 1, 2], False, [3, 3], False, False, [1, 4], False, False, False, False, [6], False, False],
             [False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, [1, 4], False, False, False, False, False, False],
             [False, False, [1, 1, 2], [2, 2], False, False, False, False, False, [4], False, False, False, False, False, False, False, False, False, [1, 3]],
             [[5], False, False, False, False, False, False, False, False, False, False, [5], False, [3, 3], False, [2, 4], False, [7], False, False],
             [False, False, [1, 4], False, [5], False, [7], False, [1, 3], False, False, False, False, False, False, False, False, False, False, [4]],
             [[1, 3], False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, [1, 1, 1, 1], [5], False, False],
             [False, False, False, False, False, False, [7], False, False, False, False, False, False, [1, 5], False, False, False, False, False, False],
             [False, False, [2, 4], False, False, False, False, [1, 1, 2], False, False, [2, 3], False, [3, 3], False, [7], False, False, False, [2, 4], False],
             [[5], False, False, False, [1, 3], False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 1]],
             [False, False, [7], False, False, False, False, False, False, False, [1, 4], False, False, False, [2, 3], False, False, False, [2, 4], False],
             [False, False, False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, [2, 3], False, [3, 3], False, False, [7], False, [1, 5], False, False, [1, 5], False],
             [False, False, [2, 4], False, [2, 4], False, [2, 4], False, False, False, False, False, False, False, False, False, False, False, False, [1, 3]],
             [False, [1, 3], False, False, False, [1, 1, 1], False, False, False, [1, 2], False, [1, 3], False, False, [4], False, False, False, False, False]],
        ]

        self.grids20x20_hard = [
            [[False, False, False, [1, 2], False, False, False, False, False, False, False, False, [1, 2], False, False, [5], False, [4], [4], False],
             [[1, 2], False, False, False, False, False, [6], False, False, [1, 5], [1, 4], False, False, False, False, False, False, False, False, False],
             [[3], False, False, False, [2, 3], False, False, False, False, False, False, False, [1, 1, 3], False, False, [2, 3], False, False, False, False],
             [False, False, False, False, [1, 1, 3], False, False, [1, 1, 2], False, False, False, False, False, False, False, False, False, False, False, [3]],
             [[5], False, [2, 3], False, False, False, False, False, [1, 2], [3], False, False, False, [1, 2, 2], False, False, [3, 3], [7], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, [7], False, False, False, False, False, False, [1, 5], False, False, False, False, False, False, [6], False],
             [[1, 2], False, [2, 4], False, False, False, False, False, False, [1, 3], False, False, False, False, False, False, [1, 1, 2], False, False, False],
             [False, False, False, False, False, False, [6], False, False, False, [6], False, False, False, False, [2, 2], False, False, False, False],
             [False, [7], False, False, False, False, False, False, [2, 4], False, False, False, [2, 4], False, False, [3], False, False, [5], False],
             [False, [3, 3], False, False, [1, 2], False, False, [2, 4], False, False, False, [2, 4], False, False, False, False, False, False, [3], False],
             [False, False, False, False, [1, 2], False, False, False, False, [1, 5], False, False, False, [1, 1, 3], False, False, False, False, False, False],
             [False, False, False, [1, 2, 2], False, False, False, False, False, False, [1, 5], False, False, False, False, False, False, [5], False, [1, 2]],
             [False, [1, 4], False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, [2, 2], False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [1, 4], [2, 3], False, False, [1, 2, 2], False, False, False, [1, 3], [2, 2], False, False, False, False, False, [1, 2], False, [1, 2]],
             [[4], False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, [1, 3], False, False, False, False],
             [False, False, False, False, [6], False, False, [6], False, False, False, False, False, False, False, [6], False, False, False, [4]],
             [False, False, False, False, False, False, False, False, False, [1, 3], [4], False, False, [6], False, False, False, False, False, [4]],
             [False, [3], [1, 2], False, [5], False, False, [1, 2], False, False, False, False, False, False, False, False, [2], False, False, False]],
            [[False, [5], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [5], False],
             [False, False, False, False, [2, 3], [1, 3], False, False, False, False, False, False, False, False, [1, 1], [2, 2], False, False, False, False],
             [False, False, [1, 2, 2], False, False, [4], False, False, [1, 5], [1, 2], [1, 1, 1], [4], False, False, [1, 2], False, False, [1, 1, 2], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [5], False, False, False, [1, 4], False, False, [1, 1, 3], False, False, [1, 2, 2], False, False, [2, 3], False, False, False, [1, 4], False],
             [False, False, [1, 3], False, False, False, [1, 5], False, False, False, False, False, False, [1, 3], False, False, False, [1, 2], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [7], False, [1, 4], [2, 3], False, [7], False, False, False, False, False, False, False],
             [False, [2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 3], False],
             [False, False, [1, 1], [2], [1, 2], False, False, [4], [5], False, False, [3], [5], False, False, [1], [1, 1], [1, 1], False, False],
             [False, False, [1, 1], [2], [1, 3], False, False, [1, 1, 1], [4], False, False, [1, 1], [4], False, False, [1, 1], [2], [1, 2], False, False],
             [False, [6], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False],
             [False, False, False, False, False, False, False, [2, 4], False, [2, 4], [2, 2], False, [2, 2], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [2, 2], False, False, False, [1, 1, 3], False, False, False, False, False, False, [1, 5], False, False, False, [2, 3], False, False],
             [False, [2, 3], False, False, False, [7], False, False, [1, 3], False, False, [1, 5], False, False, [7], False, False, False, [1, 4], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [1, 5], False, False, [1, 4], False, False, [1, 3], [1, 3], [1, 3], [1, 3], False, False, [6], False, False, [1, 2, 2], False, False],
             [False, False, False, False, [2, 3], [1, 1, 2], False, False, False, False, False, False, False, False, [1, 5], [2, 2], False, False, False, False],
             [False, [5], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [5], False]],
            [[False, [2, 2], False, False, [1, 1], [1, 1], False, False, False, False, False, False, False, False, [1, 1], [1, 1], False, False, [5], False],
             [False, False, False, [7], False, False, [1, 3], False, False, [1, 1, 2], [1, 2], False, False, [6], False, False, [2, 4], False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [[1, 2], [1, 1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 5], [1, 2]],
             [False, False, False, [1, 5], False, False, [7], False, [7], False, False, [5], False, [4], False, False, [1, 5], False, False, False],
             [False, [2, 4], False, False, False, [2, 4], False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, [7], False],
             [False, False, False, False, False, [3, 3], False, [1, 4], False, False, False, False, [1, 4], False, [1, 3], False, False, False, False, False],
             [False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, [6], False, False],
             [[4], False, False, [1, 2], False, False, [1, 5], False, [4], False, False, [7], False, [1, 5], False, False, [1, 1], False, False, [3]],
             [False, False, False, False, [3], False, False, False, False, False, False, False, False, False, False, [3], False, False, False, False],
             [False, False, False, False, [3], False, False, False, False, False, False, False, False, False, False, [3], False, False, False, False],
             [[1, 2], False, False, [1, 2], False, False, [1, 2, 2], False, [2, 2], False, False, [2, 3], False, [1, 2, 2], False, False, [1, 2], False, False, [5]],
             [False, False, [4], False, False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False],
             [False, False, False, False, False, [3, 3], False, [2, 4], False, False, False, False, [1, 4], False, [1, 1, 3], False, False, False, False, False],
             [False, [7], False, False, False, [2, 3], False, False, False, False, False, False, False, False, [2, 3], False, False, False, [2, 3], False],
             [False, False, False, [6], False, False, [1, 4], False, [1, 3], False, False, [7], False, [7], False, False, [6], False, False, False],
             [[2], [5], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], [1, 1]],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [6], False, False, [7], False, False, [1, 1, 2], [1, 4], False, False, [2, 2], False, False, [1, 4], False, False, False],
             [False, [5], False, False, [1, 1], [1, 1], False, False, False, False, False, False, False, False, [1, 1], [1, 1], False, False, [5], False]],
            [[False, False, False, False, [1, 2], False, False, False, False, False, False, [4], False, [4], False, False, [5], False, [5], False],
             [[5], False, False, False, False, False, [1, 1], False, False, [2, 4], False, False, False, False, False, False, False, False, False, False],
             [False, False, [6], False, False, False, [1, 1, 2], False, False, [2, 4], False, False, False, [2, 4], False, False, False, [6], False, False],
             [[3], False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2], [1, 3], False, False, False, False, [1, 2]],
             [False, False, False, False, [6], False, False, False, [7], False, False, False, False, False, False, False, False, False, False, False],
             [[2, 2], False, [1, 4], False, [1, 2, 2], False, False, [2, 3], False, False, [2, 4], False, [1, 4], False, False, False, False, [1, 2], [1, 1], False],
             [False, False, False, [1, 1, 2], False, False, [1, 1, 2], False, False, False, False, False, False, [2, 3], False, False, False, False, False, False],
             [[5], False, False, False, False, False, False, False, False, False, [1, 5], False, False, False, [1, 5], False, False, False, False, False],
             [False, False, False, False, False, False, [1, 2, 2], False, [2, 4], False, False, False, False, False, False, False, False, [1, 3], [1, 4], False],
             [False, [5], [1, 1, 1, 1], False, False, False, False, False, False, False, False, [2, 4], False, [2, 4], False, False, False, False, False, False],
             [False, False, False, False, False, [1, 2, 2], False, False, False, [1, 5], False, False, False, False, False, False, False, False, False, [4]],
             [False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, [1, 3], False, False, [1, 4], False, False, False],
             [False, [1, 2], [1, 5], False, False, False, False, [1, 3], False, [1, 4], False, False, [2, 2], False, False, [1, 2], False, [2, 3], False, [4]],
             [False, False, False, False, False, False, False, False, False, False, False, [2], False, False, False, [5], False, False, False, False],
             [[1, 2], False, False, False, False, [5], [1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, [5]],
             [False, False, [6], False, False, False, [6], False, False, False, [7], False, False, [1, 1, 2], False, False, False, [2, 3], False, False],
             [False, False, False, False, False, False, False, False, False, False, [2, 4], False, False, [1, 2], False, False, False, False, False, [5]],
             [False, [5], False, [3], False, False, [5], False, [5], False, False, False, False, False, False, [1, 2], False, False, False, False]],
            [[False, [4], False, False, False, [1, 3], False, False, False, False, False, False, False, False, [1, 3], False, False, False, False, False],
             [False, False, False, False, [2, 3], False, False, False, [1, 4], False, False, False, False, [7], False, False, False, False, False, [4]],
             [False, False, False, [2, 2], False, False, False, [2], False, False, False, [1, 4], False, False, False, False, [1, 3], False, False, False],
             [False, False, [6], False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, False, [1, 2], False, False],
             [False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, [3, 3], False],
             [[1, 2], False, False, False, False, False, False, False, [1, 4], False, False, False, [7], False, False, False, False, False, False, [1, 3]],
             [False, [6], False, [2, 3], False, False, [2, 4], False, False, False, [1, 2, 2], False, False, [2, 4], False, False, False, False, False, False],
             [False, False, False, False, False, [1, 5], False, False, False, [1, 4], False, False, False, False, False, [1, 2], False, [1, 2], False, False],
             [False, False, [1, 5], False, False, False, False, False, False, False, False, False, False, False, [1, 5], False, False, False, [1, 5], False],
             [False, False, False, False, False, False, [1, 1, 2], False, False, [5], [1, 3], False, [1, 4], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [6], False, [1, 3], [3], False, False, [1, 2], False, False, False, False, False, False],
             [False, [1, 1, 3], False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False],
             [False, False, [2, 3], False, [1, 2], False, False, False, False, False, [1, 5], False, False, False, [1, 5], False, False, False, False, False],
             [False, False, False, False, False, False, [1, 4], False, False, [7], False, False, False, [1, 2, 2], False, False, [1, 1, 3], False, [1, 4], False],
             [[1, 2], False, False, False, False, False, False, [7], False, False, False, [1, 4], False, False, False, False, False, False, False, [1, 2]],
             [False, [2, 2], False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, False, False],
             [False, False, [1, 1], False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, False, [6], False, False],
             [False, False, False, [5], False, False, False, False, [1, 1, 2], False, False, False, [1, 3], False, False, False, [2, 2], False, False, False],
             [[5], False, False, False, False, False, [2, 3], False, False, False, False, [1, 1, 2], False, False, False, [2, 2], False, False, False, False],
             [False, False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, [1, 2], False, False, False, [2, 2], False]],
        ]

        self.grids25x25 = [
            [[False, False, False, False, False, False, False, False, False, False, False, False, [1, 2], False, False, [1, 2], False, False, False, False, [5], False, False, False, [2]],
             [[1, 2], False, False, False, False, False, False, False, [1, 5], [1, 3], [1, 1, 2], False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False],
             [False, [2, 2], False, [2, 3], False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [1, 3], False, False, False, [2, 3], False, False, False, False, False, [7], False, [5], False, False, False, False, False, [1, 3], [2, 2], False, [6], False],
             [False, False, False, False, False, False, False, False, False, False, [6], False, False, False, [3], False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, [2, 3], False, [2, 3], False, False, False, False, False, False, False, False, [1, 1, 3], False, [1, 1, 3], False, False, False, False, False],
             [False, [1, 4], False, [1, 5], False, [2, 3], False, False, False, False, [1, 5], False, False, False, False, False, False, False, False, False, False, False, False, [6], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, [2, 3], False, False, False, [1, 2, 2], [2, 3], False, [1, 1, 2], False],
             [False, False, False, False, [6], False, False, [2, 4], False, False, False, False, [1, 5], False, False, False, False, False, False, False, False, False, [1, 3], False, False],
             [[1], [2], False, False, False, False, False, False, [1, 2], False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, False, False, False],
             [[1, 1], False, False, False, [7], False, False, False, [1, 2], [1, 3], False, False, [1, 5], False, False, [1, 2, 2], False, False, False, [7], False, False, False, False, [1, 2]],
             [False, False, [1, 1, 3], False, False, False, False, False, False, False, False, False, False, [1, 5], False, False, False, [1, 4], False, False, False, False, False, False, False],
             [False, False, False, False, [7], False, [5], False, False, False, False, False, False, False, False, False, False, False, [2, 4], False, [2, 3], False, False, False, False],
             [False, False, False, False, False, False, False, [1, 2], False, False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, [6], False, False],
             [[1, 2], False, False, False, False, [7], False, False, False, [1, 5], False, False, [1, 5], False, False, [0], [3], False, False, False, [1, 5], False, False, False, [2]],
             [False, False, False, False, False, False, False, False, False, False, [2, 4], False, False, False, False, False, [2, 2], False, False, False, False, False, False, [1, 2], [1]],
             [False, False, [1, 3], False, False, False, False, False, False, False, False, False, [1, 5], False, False, False, False, [1, 1, 1], False, False, [6], False, False, False, False],
             [False, [1, 2], False, [1, 2], [1, 1, 2], False, False, False, [2, 4], False, False, [1, 2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, [1, 5], False, [2, 4], False, [1, 5], False],
             [False, False, False, False, False, [1, 1, 2], False, [1, 5], False, False, False, False, False, False, False, False, [6], False, [7], False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, False, [6], False, False, False, False, False, False, False, False, False, False],
             [False, [3, 3], False, [5], [5], False, False, False, False, False, [5], False, [7], False, False, False, False, False, [2, 4], False, False, False, [1, 1, 2], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, [1, 5], False, [2, 3], False],
             [False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, False, [1, 1, 2], [1, 1, 3], [6], False, False, False, False, False, False, False, [1, 3]],
             [[2], False, False, False, [1, 2], False, False, False, False, [2], False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, False]],
            [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [4], False, False, False, False, [4], False, False, False, False],
             [[5], False, False, False, False, [2, 4], False, False, False, [6], False, [5], [4], False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, [6], False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, False, [6], False, [1, 2, 2], False],
             [False, [5], False, False, [1, 4], False, False, [1, 2, 2], False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, [1, 3], False, False],
             [False, False, False, False, False, [2, 3], False, False, False, False, False, False, [6], False, [2, 3], False, False, False, False, [2, 3], False, False, False, False, False],
             [[4], False, False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2]],
             [[3], False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, [1, 3], [1, 4], False, [1, 3], False, False, False, False, False, False, False, False],
             [False, False, False, [1, 1, 1], False, False, False, False, False, False, [2, 3], False, False, False, False, False, [1, 4], False, False, [7], False, [1, 2, 2], False, [6], False],
             [False, False, False, False, False, [2, 3], False, False, False, False, False, False, [1, 4], False, False, False, False, [2, 2], False, False, False, False, False, False, False],
             [[5], False, [1, 4], [1, 1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, [5]],
             [False, False, False, False, False, False, False, [2, 4], [2, 2], False, False, [2, 2], False, [1, 1, 2], False, False, False, False, False, False, False, False, False, False, False],
             [[5], False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, [2, 3], False, False, False, [1, 1, 3], [2, 3], False, False, False, False, [5]],
             [False, False, [1, 5], False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, [2, 3], False, False],
             [[2, 2], False, False, False, False, [4], [1, 3], False, False, False, [6], False, False, False, False, [1, 1, 2], False, False, False, False, False, False, False, False, [5]],
             [False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, [2, 2], False, False, [1, 1, 2], [2, 3], False, False, False, False, False, False, False],
             [[2, 2], False, False, False, [7], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [3], [5], False, [5]],
             [False, False, False, False, False, False, False, [1, 4], False, False, False, False, [1, 4], False, False, False, False, False, False, [1, 2, 2], False, False, False, False, False],
             [False, [6], False, [1, 4], False, [1, 5], False, False, [1, 2], False, False, False, False, False, [1, 5], False, False, False, False, False, False, [6], False, False, False],
             [False, False, False, False, False, False, False, False, [1, 4], False, [6], [1, 4], False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, [1]],
             [[1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False, False, [1, 1]],
             [False, False, False, False, False, [1, 3], False, False, False, False, [2, 3], False, [6], False, False, False, False, False, False, [2, 3], False, False, False, False, False],
             [False, False, [1, 2, 2], False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, [1, 5], False, False, [1, 4], False, False, [2, 4], False],
             [False, [1, 2, 2], False, [7], False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 4], False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, [2], [5], False, [2, 3], False, False, False, [2, 4], False, False, False, False, [5]],
             [False, False, False, False, [4], False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]],
            [[False, False, False, False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, [2, 2], False, [2]],
             [False, [2, 3], [3, 3], False, False, False, [1, 2, 2], False, [6], False, False, False, False, False, [3, 3], False, [1, 4], False, False, [1, 1, 1], [1, 4], False, False, False, False],
             [[1], False, False, False, False, False, False, False, False, False, False, [2, 4], False, False, False, False, False, [1, 1], False, False, False, False, False, False, False],
             [[1, 2], False, False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [5]],
             [False, False, [6], False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, [2, 3], False, False],
             [False, False, False, False, [1, 3], False, False, False, False, [2, 3], False, [1, 2], False, False, False, False, [7], False, [7], False, False, [1], False, False, [5]],
             [False, False, False, False, [1, 5], False, False, False, [1, 1], False, False, False, [6], False, False, False, [2, 2], False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, False, False, [1, 2], False, False, False, False, False],
             [False, False, [1, 2], False, [4], False, False, False, False, [1, 5], False, False, False, [1, 4], False, False, False, [1, 1, 1], False, False, False, False, False, False, [4]],
             [False, False, [1, 1, 1], False, False, False, [2, 3], False, False, False, False, False, False, False, False, False, [2, 2], False, False, False, False, False, False, False, False],
             [False, [2, 4], False, False, False, False, False, False, False, False, [3, 3], False, [1, 1, 3], False, False, [1, 1], False, False, False, False, [2, 3], False, False, False, [2]],
             [False, False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, [2, 2], False],
             [False, False, False, False, False, [1, 1, 2], False, False, False, [1, 5], False, False, False, False, False, [2, 2], False, False, False, [1, 5], False, False, False, False, False],
             [False, [1, 3], False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [5], False, False, False],
             [[2], False, False, False, [2, 3], False, False, False, False, [1, 1, 1], False, False, [7], False, [6], False, False, False, False, False, False, False, False, [2, 4], False],
             [False, False, False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, False, False, [2, 3], False, False, False, [1, 1, 2], False, False],
             [[5], False, False, False, False, False, False, [1, 1, 2], False, False, False, [7], False, False, False, [1, 2, 2], False, False, False, False, [6], False, [1, 4], False, False],
             [False, False, False, False, False, [7], False, False, False, False, False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, [1, 1], False, False, False, [5], False, False, False, [1, 2, 2], False, False, False, [1, 5], False, False, False, False],
             [[2], False, False, [2, 3], False, False, [2, 2], False, [1, 1, 1], False, False, False, False, [2, 3], False, [1, 5], False, False, False, False, [2, 3], False, False, False, False],
             [False, False, [1, 4], False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False],
             [[5], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, [4]],
             [False, False, False, False, False, False, False, [5], False, False, False, False, False, [1, 3], False, False, False, False, False, False, False, False, False, False, [2]],
             [False, False, False, False, [1, 3], [1, 4], False, False, [1, 2], False, [1, 5], False, False, False, False, False, [2, 3], False, [1, 2, 2], False, False, False, [1, 5], [1, 3], False],
             [[2], False, [5], False, False, False, False, False, False, False, False, False, False, False, [4], False, False, False, False, False, False, False, False, False, False]],
            [[False, False, False, [1, 3], False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, [1, 1], [3], False, False, [1, 2], False, False],
             [False, False, False, False, [2, 4], False, False, [7], False, False, False, [2, 4], [2, 3], False, False, False, False, False, False, False, False, False, False, False, False],
             [[1, 3], False, False, False, False, False, False, [2, 3], False, False, False, False, False, False, False, False, [1, 5], False, False, False, False, False, False, False, False],
             [False, False, False, [1, 2], [1, 3], False, False, [1, 2, 2], False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, [1, 3], False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, [3], False, False, False, [0]],
             [False, [1, 4], False, False, False, False, False, [7], False, [2, 4], False, [3, 3], False, [2, 4], False, False, [5], False, False, False, False, False, False, [3], False],
             [False, False, False, False, [1, 1, 1, 1], False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, [1, 4], False, False, False, False, False],
             [False, False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, [7], False, False, False, False, [1, 5], False, False, False],
             [[1, 2], [6], False, False, [1, 4], False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, [1, 2, 2], False, False, False, False, False, [5]],
             [False, False, False, False, False, False, False, False, False, False, False, False, [1, 5], False, False, [1, 1, 2], [1, 3], False, False, False, [1, 1, 2], False, False, False, False],
             [False, [7], False, False, [1, 4], False, False, False, False, False, [4], False, False, False, False, False, False, False, False, False, False, False, False, False, [5]],
             [False, False, False, False, False, False, [5], False, [1, 1, 1], False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False],
             [[2, 2], False, False, [6], False, False, False, False, False, [5], False, False, False, False, False, [4], False, False, False, False, False, [1, 4], False, False, [5]],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, [1, 2], False, [2, 2], False, False, False, False, False, False],
             [[2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, [5], False, False, False, False, False, [1, 4], False, False, [7], False],
             [False, False, False, False, [1, 2], False, False, False, [1, 2], [4], False, False, [2, 3], False, False, False, False, False, False, False, False, False, False, False, False],
             [[1, 3], False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, [1, 4], False, False, [6], [1, 2]],
             [False, False, False, [1, 5], False, False, False, False, [1, 5], False, False, False, False, False, False, False, False, [2, 2], False, False, False, False, False, False, False],
             [False, False, False, False, False, [1, 5], False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False, [1, 5], False, False, False, False],
             [False, [5], False, False, False, False, False, False, [2, 4], False, False, [2, 4], False, [3, 3], False, [1, 5], False, [1, 3], False, False, False, False, False, [1, 4], False],
             [[1], False, False, False, [1, 3], False, [2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [1, 3], False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, [1, 1], False, False, [5], [1, 2], False, False, False],
             [False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, False, False, [1], False, False, False, False, False, False, [1, 3]],
             [False, False, False, False, False, False, False, False, False, False, False, False, [1, 3], [1, 1, 2], False, False, False, [3], False, False, [7], False, False, False, False],
             [False, False, [1, 3], False, False, [3], [4], False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False, [1, 3], False, False, False]],
        ]

        self.grids30x30 = [
            [[[1, 1], False, False, False, [2, 2], False, False, False, False, [3], False, False, False, False, False, [1], False, False, False, False, False, False, False, [1, 2], False, False, False, False, False, False],
             [False, [2, 2], False, False, False, False, [1, 5], False, False, False, False, [1, 2], False, False, False, False, [2, 3], False, False, False, False, False, [1, 4], False, False, False, [1, 1, 2], False, False, False],
             [False, False, False, False, False, False, False, False, False, [7], False, False, [1, 3], False, [1, 4], False, False, False, False, False, [7], False, [6], False, False, False, False, False, False, [3]],
             [False, False, False, False, False, False, [4], False, False, False, False, False, False, False, False, [7], False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False],
             [False, False, False, [7], False, False, [1, 1], [1, 3], False, False, [6], False, False, False, False, False, False, [2, 4], False, False, False, [2, 3], [1, 1, 3], [2, 3], False, False, False, False, False, False],
             [False, [1, 2], False, False, False, False, False, False, False, False, False, False, [5], False, False, [6], False, False, False, False, False, False, False, False, False, False, False, [6], False, [5]],
             [False, [1, 4], False, False, False, [2, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, [1, 1, 3], False, False, False, [1, 4], [2, 2], False, False, False, False, False, False, False, [2, 2], False, [1, 2], False, False, False, False, False, [1, 1, 1], False, False, False, False, [5]],
             [False, [7], False, False, False, False, False, False, False, False, False, False, False, [1, 1], False, False, False, [1, 4], False, False, [1, 1, 2], False, False, False, False, [2, 3], False, False, False, False],
             [False, False, False, False, False, False, [2, 3], False, False, [1, 3], [2, 2], False, False, False, [6], False, False, False, False, False, False, [1, 5], False, False, False, False, False, False, False, False],
             [False, [6], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 2, 2], False, False, [1, 1, 2], False, False, [7], False, False, [1]],
             [False, False, False, [1, 1, 2], [1, 4], False, False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, False, False, False, [2, 4], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [2, 2], False, [2, 3], False, False, False, False, [1, 3], False, False, [2, 4], False, False, False, False, False, [1, 2], False, [1, 3], False, [1]],
             [[1, 1], False, False, [3, 3], False, [3], False, False, [2, 3], False, False, False, [1, 2, 2], [2, 3], False, False, False, False, False, False, [2, 4], False, False, [6], False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, [7], False, False, [1, 1, 2], False, False, False, False, False, False, [2, 2], [1, 1, 2], False, False, False, [2, 2], False, False, [2, 3], False, [1, 3], False, False, [4]],
             [[3], False, [2, 4], False, [2, 2], False, False, False, False, False, [2, 4], False, False, [1, 5], False, False, False, False, [1, 1, 2], False, [1, 3], False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [2, 3], False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, [1, 4], [1, 1, 2], False, False, False],
             [[3], False, False, [1, 4], False, False, [1, 4], False, False, [1, 2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 4], False],
             [False, False, False, False, False, False, False, False, [1, 5], False, False, False, False, False, False, [1, 1], False, False, False, [1, 1, 2], [1, 1], False, False, [7], False, False, False, False, False, False],
             [False, False, False, False, [1, 4], False, False, False, False, [1, 1, 2], False, False, [1, 2, 2], False, False, False, [5], False, False, False, False, False, False, False, False, False, False, False, [1, 5], False],
             [[5], False, False, False, False, [1, 1, 1], False, False, False, False, False, [1, 2], False, [1, 2, 2], False, False, False, False, False, False, False, [5], [1, 3], False, False, False, [1, 1, 3], False, False, False],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 4], False, False, False, [4], False],
             [[2, 2], False, [3, 3], False, False, False, False, False, False, False, False, False, False, False, [7], False, False, [1, 1, 2], False, False, False, False, False, False, False, False, False, False, [1, 2], False],
             [False, False, False, False, False, False, [1, 2], [1, 1, 3], [2, 2], False, False, False, [1, 4], False, False, False, False, False, False, [6], False, False, [1], [1, 2], False, False, [1, 2], False, False, False],
             [False, [6], False, False, False, False, False, False, False, False, False, False, False, False, [7], False, False, False, False, False, False, False, False, [5], False, False, False, False, False, False],
             [[3], False, False, False, False, False, False, [7], False, [1, 1, 3], False, False, False, False, False, [1, 4], False, [1, 4], False, False, [7], False, False, False, False, False, False, False, False, False],
             [False, False, False, [1, 1, 2], False, False, False, [2, 4], False, False, False, False, False, [6], False, False, False, False, [2, 3], False, False, False, False, [3, 3], False, False, False, False, [3, 3], False],
             [False, False, False, False, False, False, [1, 3], False, False, False, False, False, False, False, [1], False, False, False, False, False, [4], False, False, False, False, [1, 1], False, False, False, [1, 1]]]
        ]

        self.grids35x35 = [
            [[False, [1, 2], False, False, False, False, False, False, False, [1, 1], False, False, False, [3], False, False, False, False, [5], False, False, False, [1, 3], False, False, [1, 2], False, [2, 2], False, False, False, False, False, False, False],
             [False, False, [2, 2], [1, 3], False, False, False, [1, 4], False, False, False, False, False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False, False, False, False, [7], False, False, False, False, [1, 2]],
             [False, False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, [2, 3], False, False, False, False, [1, 2], False, [1, 3], False, False, False, False, False, False, False, False, False, [1, 5], False, [2, 2], False],
             [False, False, [1, 5], False, False, False, False, [7], False, [1, 1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 2], False, False, [6], [1, 4], False, False, False, False, False, [1, 3], False],
             [False, False, False, False, False, False, False, False, False, False, False, False, [2, 2], False, False, False, False, False, [1, 1], [1, 2], False, False, [1, 5], False, False, False, False, False, False, [2, 4], False, False, False, False, False],
             [False, [7], False, False, [2, 4], False, False, False, False, False, False, [1, 3], False, False, [2, 3], False, False, False, False, False, False, False, False, False, False, [2, 4], False, False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [1, 1, 1, 1], False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, [3, 3], False, False, False, False, False, False, False, False, False, False, False, False, False,
              False],
             [[5], False, False, [1, 2], False, False, False, False, [7], False, False, [1, 3], [2, 2], False, False, False, False, [1, 1, 3], False, False, False, False, [1, 2], False, False, False, False, False, [1, 1, 2], False, False, [7], False, [1, 4], False],
             [False, False, False, [4], False, False, False, False, False, False, False, [1, 2], False, False, False, False, [7], False, False, False, False, [1, 5], False, [6], False, False, False, [1, 4], False, False, False, False, False, False, False],
             [[4], False, False, False, False, [6], False, False, False, [7], False, False, False, [7], False, False, False, False, [6], False, False, False, False, False, False, [7], False, False, False, False, False, [1, 1, 3], False, False, [1, 2]],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 3], False, False],
             [False, False, False, [2, 2], False, False, False, False, [2, 3], False, False, False, [2, 4], False, False, False, [2, 3], False, False, False, [2, 3], [1, 4], False, False, False, False, [1, 3], [1, 1, 3], False, [1, 3], False, False, False, False,
              False],
             [[1, 3], False, False, False, [2, 3], False, False, [1, 3], False, False, False, False, False, [1, 5], False, False, False, False, False, False, False, False, False, [1, 4], False, False, False, [2, 2], False, False, [2, 2], False, False, False, False],
             [False, False, [7], False, False, False, False, False, [1, 5], False, False, [4], False, False, False, [2, 3], False, False, False, [2, 3], False, False, [2, 4], False, False, [2, 3], False, False, [1, 1, 1], False, False, False, False, False, [5]],
             [False, False, False, False, False, False, [2, 3], False, False, False, False, [1, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, [2, 3], False, False],
             [False, False, [1, 4], False, [1, 2], False, False, False, False, False, False, False, False, [1, 1, 1], False, False, [2, 2], False, False, False, False, [7], False, False, False, False, False, False, False, False, False, False, False, [1, 4], False],
             [[1, 2], False, False, False, [1, 3], False, False, False, False, [3, 3], False, False, False, False, False, False, [2, 2], False, [2, 3], [2, 3], False, False, False, [6], False, False, [2, 3], False, False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, [1, 1, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 3], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, [7], False, False, [1, 1, 3], False, False, False, [1, 3], [3], False, [6], False, False, False, False, False, False, [6], False, False, False, False, [1, 1, 1], False, False, False, [4]],
             [False, [2, 4], False, False, False, False, False, False, False, False, False, False, False, [7], False, False, False, False, [1, 4], False, False, [3, 3], False, False, False, False, False, False, False, False, [1, 1], False, [5], False, False],
             [False, False, [2, 3], False, False, [2, 3], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 3], False, False, False, False, [3, 3], False, False, False, False, False, False],
             [[5], False, False, False, False, False, [1, 1, 1], False, False, [7], False, False, [6], False, False, [1, 4], False, False, False, [4], False, False, False, [1, 1, 2], False, False, [1, 5], False, False, False, False, False, [6], False, False],
             [False, False, False, False, [2, 3], False, False, [2, 2], False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, [1, 2], False, False, [7], False, False, False, [1, 2]],
             [False, False, False, False, False, [1, 3], False, [1, 1, 3], [5], False, False, False, False, [4], [2, 2], False, False, False, [1, 1, 1], False, False, False, [2, 3], False, False, False, [1, 3], False, False, False, False, [1, 4], False, False, False],
             [False, False, [1, 2, 2], False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
             [[1, 2], False, False, [1, 1, 3], False, False, False, False, False, [7], False, False, False, False, False, False, [7], False, False, False, False, [7], False, False, False, [7], False, False, False, [2, 4], False, False, False, False, [3]],
             [False, False, False, False, False, False, False, [5], False, False, False, [1, 3], False, [1, 2, 2], False, False, False, False, [7], False, False, False, False, [5], False, False, False, False, False, False, False, [1, 3], False, False, False],
             [False, [1, 4], False, [6], False, False, [2, 2], False, False, False, False, False, [1, 2], False, False, False, False, [1, 1, 3], False, False, False, False, [2, 2], [1, 1, 3], False, False, [6], False, False, False, False, [2, 2], False, False, [5]],
             [False, False, False, False, False, False, False, False, False, False, False, False, False, False, [3, 3], False, False, False, False, False, False, [1, 1, 1], False, False, False, False, False, [1, 1, 1], False, False, False, False, False, False, False],
             [False, False, False, False, False, False, False, False, False, [7], False, False, False, False, False, False, False, False, False, False, [2, 3], False, False, [1, 3], False, False, False, False, False, False, [2, 3], False, False, [7], False],
             [False, False, False, False, False, [2, 3], False, False, False, False, False, False, [6], False, False, [1, 1], [1, 3], False, False, False, False, False, [2, 2], False, False, False, False, False, False, False, False, False, False, False, False],
             [False, [1, 1, 3], False, False, False, False, False, [2, 2], [5], False, False, [1, 1], False, False, False, False, False, False, False, False, False, False, False, False, False, [1, 1, 3], False, [7], False, False, False, False, [1, 5], False, False],
             [False, [2, 2], False, [1, 5], False, False, False, False, False, False, False, False, False, [2, 3], False, [2, 3], False, False, False, False, [3, 3], False, False, False, [1, 4], False, False, False, False, False, False, False, False, False, False],
             [[1, 2], False, False, False, False, [7], False, False, False, False, False, False, False, False, False, False, False, False, False, [7], False, False, False, False, False, False, False, [1, 4], False, False, False, [1, 5], [2, 2], False, False],
             [False, False, False, False, False, False, False, [5], False, [4], False, False, [1, 3], False, False, False, [3], False, False, False, False, [1, 3], False, False, False, [1, 1], False, False, False, False, False, False, False, [1, 2], False]],
        ]

        self.grids_by_size = {
            6: self.grids6x6_normal,
            '6h': self.grids6x6_hard,
            10: self.grids10x10_normal,
            '10h': self.grids10x10_hard,
            15: self.grids15x15,
            '15h': self.grids15x15_hard,
            20: self.grids20x20,
            '20h': self.grids20x20_hard,
            25: self.grids25x25,
            30: self.grids30x30,
            35: self.grids35x35,
        }

    def loop_game_xxx(self, x: int | str):
        grids = self.grids_by_size[x]
        for grid in grids:
            game = TapaGame(Grid(grid))
            solution, attempts = game.get_solution()
            assert solution is not None
            x = int(re.sub(r'\D', '', str(x))) if isinstance(x, str) else x
            assert attempts < 2 * x
            print("*", end="")
        print(" ", end="")

    def benchmark(self, x, loops_count):
        print(f"Starting benchmark for {x}x{x} grids")
        grids = self.grids_by_size[x]
        print(f"  runs {loops_count} loops of {len(grids)} boards")
        execution_time = timeit.timeit(lambda: self.loop_game_xxx(x), number=loops_count)
        print()
        print(f"  Average execution time : {execution_time / loops_count / len(grids):.3f} seconds")
        print("Benchmark finished")
        print("----------------------\n")
        return execution_time

    def run_benchmarks(self):
        size_loops_time = dict()
        size_loops_time[6] = [10, self.benchmark(6, 10)]
        size_loops_time['6h'] = [10, self.benchmark('6h', 10)]
        size_loops_time[10] = [5, self.benchmark(10, 5)]
        size_loops_time['10h'] = [5, self.benchmark('10h', 5)]
        size_loops_time[15] = [3, self.benchmark(15, 3)]
        size_loops_time['15h'] = [3, self.benchmark('15h', 3)]
        size_loops_time[20] = [2, self.benchmark(20, 2)]
        size_loops_time['20h'] = [2, self.benchmark('20h', 2)]
        size_loops_time[25] = [2, self.benchmark(25, 2)]
        size_loops_time[30] = [2, self.benchmark(30, 1)]
        size_loops_time[35] = [1, self.benchmark(35, 1)]

        print()
        print("----------------------")
        total_executions_time = sum(loop_time[1] for loop_time in size_loops_time.values())
        print(f"Total execution time: {total_executions_time:.3f} seconds")
        print("Benchmark finished")


if __name__ == '__main__':
    benchmark = TapaBenchmark()
    benchmark.run_benchmarks()
